version: 2.1

jobs:
  deploy:
    docker:
      # alpine
      - image: node:dubnium-alpine
    resource_class: medium
    working_directory: ~/repo
    steps:
      - run:
          name: Install certificates
          command: apk --update add openssl ca-certificates
      - run:
          name: Install Python3 and Pip
          command: |
            apk --update --no-cache add python3

            which python3 && python3 --version
            which pip3 && pip3 --version
      - run:
          name: Install AWS via Pip
          command: |
            pip3 install awscli

            which aws && aws --version

workflows:
  main:
    jobs:
      - deploy
