version: 2.1

jobs:
  deploy:
    docker:
      # alpine
      - image: node:dubnium-alpine
    resource_class: medium
    working_directory: ~/repo
    steps:
      - run:
          name: Install certificates
          command: apk --update add openssl ca-certificates
      - run:
          name: Install Python and Pip
          command: |
            apk --update add python py-pip

            which python && python --version
            which pip && pip --version
      - run:
          name: Install AWS via Pip
          command: pip install awscli

workflows:
  main:
    jobs:
      - deploy
